[build]
	publish = "public"
	command = "./build.sh"

[build.environment]
	HUGO_VERSION = "0.58.1"
	HUGO_BASEURL = "/"
    HUGO_ENV = "production"
    HUGO_ENABLEGITINFO = "true"

[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=604800"
